import { TodoNode } from '@/models/TodoNode';

export const TodoData: { [key in string]: TodoNode } = {
  javascript: {
    id: 'javascript',
    type: 'skill',
    title: 'Javascript',
    content: '자바스크립트는 ~~',
    prev: ['Web'],
    next: ['Typescript'],
    related: ['Python'],
  },
  typescript: {
    id: 'typescript',
    type: 'skill',
    title: 'Typescript',
    content: '타입스크립트는 ~~',
    prev: ['javascript'],
    next: ['React', 'Vue'],
    related: ['Python'],
  },
  React: {
    id: 'React',
    type: 'skill',
    title: 'React',
    content: '리액트는 ~~',
    prev: ['typescript'],
    next: ['Redux'],
    related: ['Vue'],
  },
  Vue: {
    id: 'Vue',
    type: 'skill',
    title: 'Vue',
    content: '뷰는 ~~',
    prev: ['typescript'],
    next: ['Vuex'],
    related: ['React'],
  },
  Redux: {
    id: 'Redux',
    type: 'skill',
    title: 'Redux',
    content: '리덕스는 ~~',
    prev: ['React'],
    next: ['Redux-Saga'],
    related: ['Vuex'],
  },
  python: {
    id: 'python',
    type: 'skill',
    title: 'Python',
    content: '파이썬은 ~~',
    prev: [],
    next: ['numpy', 'matplotlib', 'dataStructure'],
    related: ['computerThinking'],
  },
  computerThinking: {
    id: 'computerThinking',
    type: 'class',
    title: '컴퓨터사고',
    content: '컴퓨터사고는 ~~',
    prev: [],
    next: [],
    related: ['python'],
  },
  computerProgramming: {
    id: 'computerProgramming',
    type: 'class',
    title: '컴퓨터프로그래밍',
    content: '컴퓨터프로그래밍은 ~~',
    prev: [],
    next: [],
    related: ['C'],
  },
  C: {
    id: 'C',
    type: 'skill',
    title: 'C',
    content: 'C는 ~~',
    prev: [],
    next: ['Cpp', 'computerProgrammingAndPractice'],
    related: ['computerProgramming'],
  },
  Cpp: {
    id: 'Cpp',
    type: 'skill',
    title: 'Cpp',
    content: 'C++은 ~~',
    prev: ['C'],
    next: ['dataStructure'],
    related: ['computerProgrammingAndPractice'],
  },
  computerProgrammingAndPractice: {
    id: 'computerProgrammingAndPractice',
    type: 'class',
    title: '컴퓨터프로그래밍실습',
    content: '컴퓨터프로그래밍실습은 ~~',
    prev: ['C', 'computerProgramming'],
    next: ['dataStructure'],
    related: ['Cpp'],
  },
  numpy: {
    id: 'numpy',
    type: 'skill',
    title: 'Numpy',
    content: '넘파이는 ~~',
    prev: ['python'],
    next: ['probabilityStatistics'],
    related: ['matplotlib'],
  },
  matplotlib: {
    id: 'matplotlib',
    type: 'skill',
    title: 'Matplotlib',
    content: '맷플롯립은 ~~',
    prev: ['python'],
    next: ['probabilityStatistics'],
    related: ['numpy'],
  },
  dataStructure: {
    id: 'dataStructure',
    type: 'class',
    title: '자료구조',
    content: '자료구조는 ~~',
    prev: ['python', 'Cpp', 'computerProgrammingAndPractice'],
    next: ['algorithm'],
    related: [],
  },
  algorithm: {
    id: 'algorithm',
    type: 'class',
    title: '알고리즘',
    content: '알고리즘은 ~~',
    prev: ['dataStructure'],
    next: ['probabilityStatistics'],
    related: [],
  },
  probabilityStatistics: {
    id: 'probabilityStatistics',
    type: 'class',
    title: '확률과 통계',
    content: '확률과 통계는 ~~',
    prev: ['numpy', 'matplotlib'],
    next: ['machineLearning'],
    related: [],
  },
  machineLearning: {
    id: 'machineLearning',
    type: 'class',
    title: '머신러닝',
    content: '머신러닝은 ~~',
    prev: ['probabilityStatistics'],
    next: ['deepLearning', 'computerVision'],
    related: [],
  },
  deepLearning: {
    id: 'deepLearning',
    type: 'class',
    title: '딥러닝',
    content: '딥러닝은 ~~',
    prev: ['machineLearning'],
    next: [],
    related: [],
  },
  computerVision: {
    id: 'computerVision',
    type: 'class',
    title: '컴퓨터비전',
    content: '컴퓨터비전은 ~~',
    prev: ['machineLearning'],
    next: [],
    related: [],
  },
};
