import { TodoNode } from '@/models/TodoNode';

export const TodoData: { [key in string]: TodoNode } = {
  html: {
    id: 'html',
    type: 'skill',
    title: 'HTML',
    content:
      '<img width="20px" src="https://i.imgur.com/dstWtH7.png" /><br>HTML은 웹 페이지를 구성하는 데 사용되는 마크업 언어입니다. 웹 페이지의 구조, 내용, 그리고 표현 방식을 정의하기 위해 사용됩니다. HTML은 웹 개발의 기초 요소로서, 웹 브라우저가 이해하고 해석하여 사용자에게 내용을 제공합니다.',
    prev: [],
    next: ['javascript'],
    related: ['css'],
  },
  css: {
    id: 'css',
    type: 'skill',
    title: 'css',
    content:
      '<img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/css3/css3-original.svg" /><br>CSS는 Cascading Style Sheets의 약자로, HTML이나 XML과 같은 마크업 언어로 작성된 문서의 스타일과 레이아웃을 정의하기 위해 사용되는 스타일 시트 언어입니다. CSS는 웹 페이지의 디자인, 색상, 레이아웃, 폰트 등의 시각적인 요소를 지정하여 웹 페이지를 보다 예쁘고 일관성 있게 표현할 수 있습니다. CSS는 HTML과 함께 사용되어 웹 개발자들이 웹 페이지의 스타일을 쉽게 관리하고 수정할 수 있게 해줍니다.',
    prev: [],
    next: ['javascript'],
    related: ['html'],
  },
  javascript: {
    id: 'javascript',
    type: 'skill',
    title: 'javascript',
    content:
      '<img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-original.svg" /><br>JavaScript(JS)는 웹 페이지를 동적으로 만들기 위해 사용되는 프로그래밍 언어입니다. HTML과 CSS와 함께 사용되며, 웹 브라우저에서 클라이언트 측 스크립팅 언어로 실행됩니다. JavaScript를 사용하면 사용자와 상호작용하고, 이벤트에 응답하며, 웹 페이지의 내용을 동적으로 변경하고 조작할 수 있습니다. JS는 다양한 기능과 라이브러리를 제공하여 웹 애플리케이션의 개발과 사용자 경험을 향상시킬 수 있습니다.',
    prev: ['html', 'css'],
    next: ['typescript'],
    related: [],
  },
  typescript: {
    id: 'typescript',
    type: 'skill',
    title: 'typescript',
    content:
      '<img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/typescript/typescript-original.svg" /><br>TypeScript (TS)는 Microsoft에서 개발한 정적 타입을 지원하는 JavaScript의 상위 집합 언어입니다. TS는 JavaScript의 모든 기능을 포함하면서도 추가적인 정적 타입 체크와 객체 지향 프로그래밍 기능을 제공합니다. TS는 개발자가 코드를 더 안정적으로 작성하고 유지할 수 있도록 도와주며, 대규모 프로젝트에서 효율적인 협업과 유지 보수를 가능하게 합니다.',
    prev: ['javascript'],
    next: ['react', 'vue'],
    related: [],
  },
  react: {
    id: 'react',
    type: 'skill',
    title: 'react',
    content:
      '<img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg" /><br/>React는 Facebook에서 개발된 사용자 인터페이스(UI) 라이브러리로, 웹 및 모바일 애플리케이션 개발에 사용됩니다. React는 컴포넌트 기반 아키텍처를 사용하여 재사용 가능하고 모듈화된 UI 요소를 만들고 관리할 수 있습니다. Virtual DOM을 활용하여 성능을 최적화하며, 단방향 데이터 흐름을 통해 애플리케이션 상태 관리를 용이하게 합니다. React는 커뮤니티의 활발한 생태계와 다양한 지원 도구를 통해 개발자들에게 많은 혜택을 제공합니다.',
    prev: ['typescript'],
    next: ['redux'],
    related: ['vue'],
  },
  vue: {
    id: 'vue',
    type: 'skill',
    title: 'vue',
    content:
      '<img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/vuejs/vuejs-original.svg" /><br>Vue.js는 사용자 인터페이스(UI)를 개발하기 위한 점진적인 자바스크립트 프레임워크입니다. 리액트(React)와 앵귤러(Angular)의 중간 지점에 위치하며, 가볍고 유연한 성격을 가지고 있습니다. Vue.js는 단일 파일 컴포넌트 구조와 양방향 데이터 바인딩을 강조하여 개발자들이 손쉽게 UI를 구성하고 상태를 관리할 수 있도록 도와줍니다.',
    prev: ['typescript'],
    next: [],
    related: ['react'],
  },
  redux: {
    id: 'redux',
    type: 'skill',
    title: 'redux',
    content:
      'Redux는 JavaScript 애플리케이션의 상태 관리를 위한 예측 가능한 상태 컨테이너입니다. 애플리케이션의 모든 상태가 단일 저장소에 저장되며, 상태의 변경은 순수 함수인 리듀서를 통해 관리됩니다. Redux는 Flux 아키텍처를 기반으로 하며, 애플리케이션의 복잡한 상태를 효율적으로 관리하고 상태 변화를 추적하기 위해 사용됩니다. Redux는 React뿐만 아니라 Angular, Vue와 같은 다양한 프론트엔드 프레임워크와 함께 사용할 수 있습니다.',
    prev: ['react'],
    next: [],
    related: [],
  },
  python: {
    id: 'python',
    type: 'skill',
    title: 'python',
    content:
      'Python은 간결하고 읽기 쉬운 문법을 가진 고수준 프로그래밍 언어로, 다양한 도메인에서 사용되는 인기 있는 언어입니다. 파이썬은 다양한 라이브러리와 풍부한 생태계를 갖추고 있어 데이터 분석, 웹 개발, 인공지능, 자동화 등 다양한 영역에서 활용됩니다. 또한 크로스 플랫폼 지원과 커뮤니티의 활발한 지원으로 개발자들에게 편리하고 생산적인 환경을 제공합니다.',
    prev: [],
    next: [
      'numpy',
      'matplotlib',
      'Pandas',
      'SciPy',
      'ScikitLearn',
      'TensorFlow',
      'PyTorch',
      'Django',
      'Flask',
      'Tkinter',
      'PyQt',
      'Kivy',
    ],
    related: [
      'computerThinking',
      'dataStrucutre',
      'algorithm',
      'probabilityStatistics',
      'machineLearning',
      'beakJoon',
      'codeForce',
      'programmers',
      'codeTree',
      'codeUp',
    ],
  },
  numpy: {
    id: 'numpy',
    type: 'skill',
    title: 'Numpy',
    content:
      'NumPy는 파이썬에서 수치 계산과 과학적인 데이터 처리를 위한 핵심 라이브러리입니다. 다차원 배열 객체인 ndarray를 제공하여 벡터화 연산과 브로드캐스팅 등의 기능을 효율적으로 수행할 수 있습니다. NumPy는 선형 대수, 푸리에 변환, 난수 생성 등 다양한 수학적인 연산과 함수를 제공하며, 데이터 분석, 머신러닝, 이미지 처리 등 다양한 분야에서 널리 사용됩니다.',
    prev: ['python'],
    next: [],
    related: ['matplotlib', 'probabilityStatistics', 'machineLearning'],
  },
  matplotlib: {
    id: 'matplotlib',
    type: 'skill',
    title: 'Matplotlib',
    content:
      'Matplotlib는 파이썬에서 데이터 시각화를 위한 강력한 라이브러리로, 다양한 그래프와 플롯을 생성할 수 있습니다. 라인 플롯, 산점도, 막대 그래프, 히스토그램 등 다양한 시각화 스타일과 옵션을 제공하여 데이터를 직관적으로 이해할 수 있게 도와줍니다. Matplotlib는 파이썬 데이터 과학 생태계에서 핵심적인 역할을 하며, NumPy와 함께 자주 사용되는 시각화 도구입니다.',
    prev: ['python'],
    next: [],
    related: ['numpy', 'probabilityStatistics', 'machineLearning'],
  },
  Pandas: {
    id: 'Pandas',
    type: 'skill',
    title: 'Pandas',
    content:
      'Pandas는 파이썬에서 데이터 조작과 분석을 위한 강력한 라이브러리로, 데이터 구조와 데이터 분석을 위한 도구를 제공합니다. 주로 테이블 형태의 데이터를 다루는데 특화되어 있으며, 데이터 필터링, 정렬, 그룹화, 결측치 처리 등 다양한 데이터 조작 작업을 간편하게 수행할 수 있습니다. Pandas는 데이터 과학 및 머신러닝 분야에서 널리 사용되며, 데이터 전처리부터 분석 결과 시각화까지 다양한 작업에 유용한 도구입니다.',
    prev: ['python'],
    next: [],
    related: [],
  },
  SciPy: {
    id: 'SciPy',
    type: 'skill',
    title: 'SciPy',
    content:
      'SciPy는 파이썬의 과학 및 수학적인 계산을 위한 강력한 오픈 소스 라이브러리입니다. 다양한 과학적인 작업에 사용되는 여러 모듈과 함수를 제공하며, 선형 대수, 최적화, 통계, 신호 및 이미지 처리, 수치적 적분 등 다양한 기능을 포함하고 있습니다. SciPy는 NumPy와 밀접하게 연결되어 높은 수준의 수치 계산 및 데이터 분석을 수행할 수 있습니다.',
    prev: ['python'],
    next: [],
    related: [],
  },
  ScikitLearn: {
    id: 'ScikitLearn',
    type: 'skill',
    title: 'ScikitLearn',
    content:
      'Scikit-Learn은 파이썬에서 머신러닝과 데이터 분석을 위한 강력한 라이브러리입니다. Scikit-Learn은 사용하기 쉬운 API와 다양한 알고리즘을 제공하여 분류, 회귀, 군집화, 차원 축소 등 다양한 머신러닝 작업을 수행할 수 있습니다. 또한 데이터 전처리, 피처 추출, 모델 평가 등 머신러닝 파이프라인 구축을 위한 다양한 도구를 제공하여 효율적인 모델 개발을 지원합니다.',
    prev: ['python'],
    next: [],
    related: [],
  },
  TensorFlow: {
    id: 'TensorFlow',
    type: 'skill',
    title: 'TensorFlow',
    content:
      'TensorFlow는 구글에서 개발한 딥러닝 및 기계 학습을 위한 오픈 소스 라이브러리로, 다양한 인공신경망 모델을 구축하고 훈련시키는 데 사용됩니다. TensorFlow는 유연한 그래프 기반 계산 모델을 제공하며, CPU 및 GPU를 활용하여 대규모 데이터셋에서 고성능 계산을 수행할 수 있습니다. 또한 TensorFlow는 자동 미분, 모델 배포, 모바일 및 임베디드 장치 지원 등 다양한 기능을 제공하여 딥러닝 응용 프로그램의 개발과 배포를 용이하게 합니다.',
    prev: ['python'],
    next: [],
    related: ['machineLearning', 'deepLearning', 'computerVision'],
  },
  PyTorch: {
    id: 'PyTorch',
    type: 'skill',
    title: 'PyTorch',
    content: '파이토치는 ~~',
    prev: ['python'],
    next: [],
    related: [],
  },
  Django: {
    id: 'Django',
    type: 'skill',
    title: 'Django',
    content: '장고는 ~~',
    prev: ['python'],
    next: [],
    related: [],
  },
  Flask: {
    id: 'Flask',
    type: 'skill',
    title: 'Flask',
    content: '플라스크는 ~~',
    prev: ['python'],
    next: [],
    related: [],
  },
  Tkinter: {
    id: 'Tkinter',
    type: 'skill',
    title: 'Tkinter',
    content: '티킨터는 ~~',
    prev: ['python'],
    next: [],
    related: [],
  },
  PyQt: {
    id: 'PyQt',
    type: 'skill',
    title: 'PyQt',
    content: '파이큐티는 ~~',
    prev: ['python'],
    next: [],
    related: [],
  },
  Kivy: {
    id: 'Kivy',
    type: 'skill',
    title: 'Kivy',
    content: '키비는 ~~',
    prev: ['python'],
    next: [],
    related: [],
  },
  FreshMan: {
    id: 'FreshMan',
    type: 'grade',
    title: '1학년',
    content: '1학년 과목들입니다.',
    prev: [],
    next: ['sophomore'],
    related: [
      'computerProgramming',
      'computerProgrammingAndPractice',
      'computerThinking',
    ],
  },

  computerThinking: {
    id: 'computerThinking',
    type: 'class',
    title: '컴퓨터사고',
    content: '컴퓨터사고는 ~~',
    prev: ['FreshMan'],
    next: [],
    related: ['python'],
  },
  computerProgramming: {
    id: 'computerProgramming',
    type: 'class',
    title: '컴퓨터프로그래밍',
    content: '컴퓨터프로그래밍은 ~~',
    prev: ['FreshMan'],
    next: ['computerProgrammingAndPractice'],
    related: ['C'],
  },
  computerProgrammingAndPractice: {
    id: 'computerProgrammingAndPractice',
    type: 'class',
    title: '컴퓨터프로그래밍실습',
    content:
      '컴퓨터 프로그래밍 실습은 이론적인 개념을 실제로 적용하여 프로그래밍 기술을 연마하는 과목입니다. 이 과목에서는 프로그래밍 언어를 사용하여 실제 문제를 해결하고, 알고리즘을 구현하며, 프로그램 디버깅 및 테스트 등을 경험합니다. 컴퓨터 프로그래밍 실습은 학습한 이론을 실제로 적용하고 개발 능력을 향상시키기 위한 중요한 활동으로, 실제 프로그래밍 프로젝트나 예제를 통해 실전 개발 환경에 대한 경험을 쌓을 수 있습니다.',
    prev: ['FreshMan', 'computerProgramming'],
    next: ['dataStrucutre'],
    related: ['Cpp', 'C'],
  },
  C: {
    id: 'C',
    type: 'skill',
    title: 'C',
    content:
      '<img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/c/c-original.svg" /><br/>C는 저수준 프로그래밍 언어로, 시스템 프로그래밍이나 하드웨어와의 직접적인 상호작용에 주로 사용됩니다. C는 간단하면서도 효율적인 프로그래밍을 가능하게 합니다.',
    prev: [],
    next: ['Cpp', 'GTK', 'OpenSSL', 'APR'],
    related: [
      'computerProgramming',
      'computerProgrammingAndPractice',
      'dataStrucutre',
      'algorithm',
      'beakJoon',
      'codeForce',
      'programmers',
      'codeTree',
      'codeUp',
    ],
  },
  GTK: {
    id: 'GTK',
    type: 'skill',
    title: 'GTK',
    content:
      'GTK는 C로 작성된 크로스 플랫폼 위젯 툴킷입니다. GTK는 다양한 운영체제에서 사용할 수 있으며, GTK를 사용하여 GUI를 만들 수 있습니다.',
    prev: ['C'],
    next: [],
    related: [],
  },
  OpenSSL: {
    id: 'OpenSSL',
    type: 'skill',
    title: 'OpenSSL',
    content:
      'OpenSSL은 C로 작성된 오픈소스 라이브러리로, SSL과 TLS 프로토콜을 구현합니다. OpenSSL은 네트워크 통신에서 보안을 위해 사용됩니다.',
    prev: ['C'],
    next: [],
    related: [],
  },
  APR: {
    id: 'APR',
    type: 'skill',
    title: 'APR',
    content:
      'APR은 C로 작성된 Apache Portable Runtime의 약자입니다. APR은 Apache HTTP Server의 핵심 라이브러리로, 다양한 운영체제에서 사용할 수 있습니다.',
    prev: ['C'],
    next: [],
    related: [],
  },

  Cpp: {
    id: 'Cpp',
    type: 'skill',
    title: 'Cpp',
    content:
      '<img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/cplusplus/cplusplus-original.svg" /><br /> C++은 객체지향 프로그래밍을 지원하는 일반적인 목적의 프로그래밍 언어입니다. C++은 C에 대한 확장으로, C와의 호환성을 가지면서도 추가적인 기능을 제공합니다.',
    prev: ['C'],
    next: ['Qt', 'Boost'],
    related: [
      'computerProgrammingAndPractice',
      'dataStrucutre',
      'OOP',
      'algorithm',
      'beakJoon',
      'codeForce',
      'programmers',
      'codeTree',
      'codeUp',
    ],
  },
  Qt: {
    id: 'Qt',
    type: 'skill',
    title: 'Qt',
    content:
      'Qt는 C++로 작성된 크로스 플랫폼 응용 프로그램 개발 프레임워크입니다. Qt는 GUI 프로그래밍을 위한 다양한 기능을 제공합니다.',
    prev: ['Cpp'],
    next: [],
    related: [],
  },
  Boost: {
    id: 'Boost',
    type: 'skill',
    title: 'Boost',
    content:
      'Boost는 C++ 표준 라이브러리를 보완하고 확장하기 위한 다양한 기능을 제공하는 라이브러리 모음입니다. 스마트 포인터, 스레딩, 정규 표현식 등의 기능을 포함합니다.',
    prev: ['Cpp'],
    next: [],
    related: [],
  },

  Java: {
    id: 'Java',
    type: 'skill',
    title: 'Java',
    content:
      'Java는 객체지향 프로그래밍 언어로, 다양한 플랫폼에서 동작하는 애플리케이션 개발에 주로 사용됩니다. Java는 가상 머신을 통해 플랫폼 독립성을 제공합니다.',
    prev: [],
    next: ['JavaFX', 'JUnit', 'Spring', 'JSP', 'Hibernate', 'JPA'],
    related: [
      'OOP',
      'DesignPattern',
      'algorithm',
      'beakJoon',
      'codeForce',
      'programmers',
      'codeTree',
      'codeUp',
    ],
  },
  JavaFX: {
    id: 'JavaFX',
    type: 'skill',
    title: 'JavaFX',
    content:
      'JavaFX는 Java로 작성된 GUI 플랫폼입니다. JavaFX는 다양한 플랫폼에서 동작하며, FXML을 통해 GUI를 설계할 수 있습니다.',
    prev: ['Java'],
    next: [],
    related: [],
  },
  JUnit: {
    id: 'JUnit',
    type: 'skill',
    title: 'JUnit',
    content:
      'JUnit은 Java로 작성된 단위 테스트 프레임워크입니다. JUnit은 테스트 케이스를 작성하고 실행할 수 있으며, 테스트 결과를 확인할 수 있습니다.',
    prev: ['Java'],
    next: [],
    related: [],
  },
  Spring: {
    id: 'Spring',
    type: 'skill',
    title: 'Spring',
    content:
      'Spring은 Java로 작성된 애플리케이션 프레임워크입니다. Spring은 의존성 주입을 통해 객체 간의 관계를 설정하고, AOP를 통해 애플리케이션을 모듈화할 수 있습니다.',
    prev: ['Java'],
    next: [],
    related: [],
  },
  JSP: {
    id: 'JSP',
    type: 'skill',
    title: 'JSP',
    content:
      'JSP는 Java로 작성된 서버 사이드 스크립트 언어입니다. JSP는 HTML 내에 Java 코드를 삽입하여 동적인 웹 페이지를 생성할 수 있습니다.',
    prev: ['Java'],
    next: [],
    related: [],
  },
  Hibernate: {
    id: 'Hibernate',
    type: 'skill',
    title: 'Hibernate',
    content:
      'Hibernate는 Java로 작성된 ORM(Object Relational Mapping) 프레임워크입니다. Hibernate는 객체와 데이터베이스 간의 매핑을 통해 데이터베이스를 사용할 수 있습니다.',
    prev: ['Java'],
    next: [],
    related: ['mysql'],
  },
  JPA: {
    id: 'JPA',
    type: 'skill',
    title: 'JPA',
    content:
      'JPA는 Java로 작성된 ORM(Object Relational Mapping) 프레임워크입니다. JPA는 Hibernate를 포함하여 다양한 ORM 프레임워크를 사용할 수 있습니다.',
    prev: ['Java'],
    next: [],
    related: [],
  },
  Sophomore: {
    id: 'Sophomore',
    type: 'grade',
    title: '2학년',
    content: '2학년 과목들 입니다.',
    prev: ['FreshMan'],
    next: ['junior'],
    related: [
      'DataStructure',
      'Algorithm',
      'ProbabilityStatistics',
      'openSource',
      'ProgrammingLanguage',
      'OOP',
    ],
  },
  probabilityStatistics: {
    id: 'probabilityStatistics',
    type: 'class',
    title: '확률과 통계',
    content:
      '확률과 통계는 사건이 발생할 확률과 데이터의 패턴을 분석하는 수학적인 기법과 원리를 다루는 과목입니다. 이 과목에서는 확률 분포, 표본 추출, 가설 검정, 회귀 분석 등을 다루며, 데이터를 수집, 정리, 해석하여 신뢰할 수 있는 결론을 도출하는 방법을 학습합니다. 확률과 통계는 다양한 분야에서 데이터 분석, 예측, 의사 결정 등에 활용되며, 학문적이고 실용적인 통계적 사고와 능력을 배양합니다.',
    prev: [],
    next: ['machineLearning'],
    related: ['numpy', 'matplotlib', 'python'],
  },
  ProgrammingLanguage: {
    id: 'ProgrammingLanguage',
    type: 'class',
    title: '프로그래밍언어론',
    content:
      '프로그래밍 언어론은 프로그래밍 언어의 구문, 의미론, 동작 원리 등을 연구하는 컴퓨터 과학의 핵심 과목입니다. 이 과목에서는 프로그래밍 언어의 설계 원칙, 구문 분석, 타입 시스템, 실행 모델 등을 다루며, 다양한 언어의 비교와 분석을 통해 프로그래밍 언어의 특성을 이해합니다. 프로그래밍 언어론은 개발자들이 효과적이고 안정적인 소프트웨어를 개발하기 위해 필요한 기초 이론을 제공합니다.',
    prev: ['OOP'],
    next: ['compiler'],
    related: ['python', 'C', 'Cpp', 'Java', 'javascript', 'typescript'],
  },
  openSource: {
    id: 'openSource',
    type: 'class',
    title: '오픈소스소프트웨어',
    content:
      '오픈소스소프트웨어는 소스코드를 공개하여 누구나 자유롭게 사용, 복제, 배포, 수정할 수 있는 소프트웨어를 말합니다. 이 과목에서는 오픈소스의 개념과 역사, 그리고 오픈소스 라이선스에 대해 학습합니다. 또한 오픈소스의 장점과 단점, 그리고 오픈소스 활동에 참여하는 방법과 오픈소스 프로젝트를 진행하는 방법을 배웁니다. 오픈소스는 소프트웨어 개발에 있어서 중요한 역할을 하고 있으며, 오픈소스 활동은 개발자들의 협업과 커뮤니케이션 능력을 향상시키는 데 도움을 줍니다.',
    prev: [],
    next: [],
    related: ['git'],
  },
  dataStrucutre: {
    id: 'dataStrucutre',
    type: 'class',
    title: '자료구조',
    content:
      '자료구조는 데이터를 조직화하고 저장하는 방법을 연구하는 컴퓨터 과학의 핵심 과목입니다. 이 과목에서는 배열, 연결 리스트, 스택, 큐, 트리, 그래프 등의 다양한 데이터 구조와 그들의 동작, 효율성을 학습합니다. 자료구조는 알고리즘의 효율성과 문제 해결 능력을 향상시키는 데 중요한 역할을 합니다.',
    prev: ['computerProgrammingAndPractice'],
    next: ['algorithm'],
    related: ['python', 'C', 'Cpp'],
  },
  algorithm: {
    id: 'algorithm',
    type: 'class',
    title: '알고리즘',
    content:
      '알고리즘 과목은 문제를 해결하기 위한 단계적인 절차와 규칙을 설계하는 기술과 이론을 다루는 과목입니다. 이 과목에서는 효율적인 알고리즘 설계와 분석 기법, 자료 구조의 활용 등을 학습하여 다양한 문제를 효율적으로 해결하는 방법을 배웁니다. 알고리즘 과목은 프로그래밍, 데이터 분석, 인공지능 등 다양한 컴퓨터 과학 분야에서 필수적인 기반 지식을 제공합니다.',
    prev: ['dataStrucutre'],
    next: ['beakJoon', 'programmers', 'codeForce', 'codeTree', 'codeUp'],
    related: ['python', 'C', 'Cpp', 'Java'],
  },
  OOP: {
    id: 'OOP',
    type: 'class',
    title: '객체지향프로그래밍',
    content: '객체지향프로그래밍은 ~~',
    prev: [],
    next: ['DesignPattern', 'ProgrammingLanguage'],
    related: ['Cpp', 'Java'],
  },
  junior: {
    id: 'junior',
    type: 'grade',
    title: '3학년',
    content: '3학년 과목들입니다.',
    prev: ['sophomore'],
    next: ['senior'],
    related: [
      'computerArchitecture',
      'DesignPattern',
      'systemProgramming',
      'dataMining',
      'dataTransfer',
      'computerNetwork',
      'machineLearning',
      'NLP',
      'dataBase',
      'operatingSystem',
      'compiler',
    ],
  },
  computerArchitecture: {
    id: 'computerArchitecture',
    type: 'class',
    title: '컴퓨터구조',
    content:
      '컴퓨터 구조는 컴퓨터 시스템의 구성과 동작 원리를 다루는 과목으로, 하드웨어와 소프트웨어 간의 상호작용과 데이터 처리를 이해하는 데 중점을 둡니다. 이 과목에서는 중앙처리장치(CPU), 기억장치, 입출력 장치 등의 구성 요소와 데이터 플로우, 명령어 실행, 인터럽트 처리 등의 주요 개념을 학습합니다. 컴퓨터 구조는 컴퓨터 시스템의 성능, 효율성, 보안 등을 이해하고 설계하기 위한 필수적인 이론과 기술을 제공합니다.',
    prev: [],
    next: ['operatingSystem'],
    related: ['C', 'assembly'],
  },
  systemProgramming: {
    id: 'systemProgramming',
    type: 'class',
    title: '시스템프로그래밍',
    content:
      '시스템 프로그래밍은 운영체제와 하드웨어를 다루는 프로그램 개발에 중점을 둔 과목으로, 저수준의 시스템 기능을 활용하여 효율적인 소프트웨어를 구현하는 기술을 학습합니다. 이 과목에서는 시스템 호출, 파일 입출력, 프로세스 및 스레드 관리, 메모리 관리 등과 같은 시스템 레벨의 프로그래밍 작업을 다루며, 시스템의 성능, 보안, 안정성을 고려한 프로그램 개발 능력을 강화합니다. 시스템 프로그래밍은 운영체제와의 인터페이스를 통해 하드웨어를 제어하고 다양한 시스템 리소스를 효율적으로 활용하는 데 중요한 역할을 합니다.',
    prev: [],
    next: ['operatingSystem'],
    related: ['C'],
  },

  DesignPattern: {
    id: 'DesignPattern',
    type: 'class',
    title: '디자인패턴',
    content: '디자인패턴은 ~~',
    prev: ['OOP'],
    next: [],
    related: ['Java', 'python'],
  },
  dataMining: {
    id: 'dataMining',
    type: 'class',
    title: '데이터마이닝',
    content:
      '데이터마이닝은 대규모 데이터에서 유용한 정보와 패턴을 발견하고 추출하는 기술과 과정을 다루는 과목입니다. 이 과목에서는 데이터 전처리, 분석 알고리즘, 모델링 기법 등을 학습하여 데이터로부터 의미 있는 인사이트를 도출하고 예측 모델을 구축하는 방법을 배웁니다. 데이터마이닝은 비즈니스 인텔리전스, 마케팅 전략, 금융 분석 등 다양한 분야에서 의사 결정과 문제 해결을 위해 활용됩니다.',
    prev: [],
    next: ['dataBaseDesign'],
    related: [],
  },
  dataTransfer: {
    id: 'dataTransfer',
    type: 'class',
    title: '데이터통신',
    content:
      '데이터 통신은 컴퓨터 네트워크를 통해 데이터를 전송하는 방법과 프로토콜을 다루는 과목입니다. 이 과목에서는 데이터 전송의 기본 원리, 물리적인 전송 매체, 데이터 인코딩, 패킷 스위칭, 라우팅 등에 대해 학습하며, TCP/IP 프로토콜 스택을 중심으로 네트워크 프로토콜의 동작과 구성을 이해합니다. 데이터 통신 과목은 실제 네트워크 구축과 관리, 네트워크 보안 등 다양한 네트워크 관련 업무에 필요한 기술과 이해력을 강화합니다.',
    prev: [],
    next: ['computerNetwork'],
    related: [],
  },

  machineLearning: {
    id: 'machineLearning',
    type: 'class',
    title: '머신러닝',
    content:
      '머신러닝은 컴퓨터 시스템이 데이터로부터 학습하고 패턴을 인식하여 자동으로 결정을 내리는 인공지능 분야입니다. 이 과목에서는 데이터 분석 기법, 학습 알고리즘, 모델 평가 및 최적화 등을 다루며, 지도 학습, 비지도 학습, 강화 학습 등의 다양한 머신러닝 방법론을 학습합니다. 머신러닝은 예측, 분류, 군집화 등 다양한 응용 분야에서 활용되며, 데이터 기반 의사 결정과 패턴 인식에 중요한 역할을 합니다.',
    prev: ['probabilityStatistics'],
    next: ['deepLearning', 'computerVision', 'NLP'],
    related: ['numpy', 'matplotlib', 'python', 'TensorFlow'],
  },
  NLP: {
    id: 'NLP',
    type: 'class',
    title: '자연어처리',
    content:
      '자연어 처리(Natural Language Processing, NLP)는 인간의 언어를 컴퓨터가 이해하고 처리할 수 있는 형태로 변환하는 기술입니다. 자연어 처리는 컴퓨터가 텍스트 데이터를 분석, 이해, 생성하고, 문장의 의미를 추출하거나 감성 분석, 기계 번역, 질의응답 시스템 등 다양한 언어 기반 작업을 수행할 수 있게 합니다. 자연어 처리는 토큰화, 품사 태깅, 구문 분석, 개체명 인식, 단어 임베딩 등 다양한 기술과 알고리즘을 활용하여 구현됩니다. 이를 통해 자연어 처리 기술은 자동화된 챗봇, 문서 분류, 텍스트 요약, 정보 추출 등 다양한 실전 응용 프로그램에서 활용됩니다.',
    prev: ['machineLearning'],
    next: [],
    related: ['TensorFlow'],
  },

  compiler: {
    id: 'compiler',
    type: 'class',
    title: '컴파일러',
    content:
      '컴파일러 과목은 프로그래밍 언어로 작성된 소스 코드를 기계어로 변환하는 컴파일러의 동작 원리와 설계에 대해 다루는 컴퓨터 과학의 핵심 과목입니다. 이 과목에서는 어휘 분석, 구문 분석, 의미 분석, 코드 생성 등의 단계를 학습하며, 언어의 문법에 따라 소스 코드를 분석하고 변환하는 방법을 이해합니다. 컴파일러 과목은 프로그래밍 언어와 컴퓨터 아키텍처 사이의 인터페이스를 이해하고, 효율적인 프로그램 실행을 위해 필수적인 지식을 제공합니다.',
    prev: ['ProgrammingLanguage'],
    next: [],
    related: [],
  },
  operatingSystem: {
    id: 'operatingSystem',
    type: 'class',
    title: '운영체제',
    content:
      '운영체제는 컴퓨터 시스템의 핵심 소프트웨어로, 하드웨어와 애플리케이션 사이에서 중재자 역할을 합니다. 이 과목에서는 프로세스 스케줄링, 메모리 관리, 파일 시스템, 입출력 관리 등의 주요 개념과 알고리즘을 다루며, 컴퓨터 시스템의 자원을 효율적으로 관리하고 사용자 및 애플리케이션의 요구를 충족시키는 역할을 학습합니다. 운영체제 과목은 시스템의 안정성, 보안, 성능을 향상시키기 위한 필수적인 이론과 기술을 제공합니다.',
    prev: ['computerArchitecture'],
    next: [],
    related: [],
  },

  computerNetwork: {
    id: 'computerNetwork',
    type: 'class',
    title: '컴퓨터네트워크',
    content:
      '컴퓨터 네트워크는 컴퓨터 시스템 간에 데이터와 자원을 공유하기 위한 연결된 구조로, 정보를 교환하고 통신하는 방법을 다루는 과목입니다. 이 과목에서는 네트워크 구성, 프로토콜, 라우팅, 데이터 전송 등의 주요 개념과 기술을 학습하며, 이더넷, TCP/IP, 라우터, 스위치 등의 네트워크 장비와 동작 원리를 이해합니다. 컴퓨터 네트워크 과목은 실제 네트워크 설계, 구축, 관리 및 보안에 필요한 기반 지식을 제공합니다.',
    prev: ['dataTransfer'],
    next: [],
    related: [],
  },
  dataBase: {
    id: 'dataBase',
    type: 'class',
    title: '데이터베이스',
    content:
      '데이터베이스는 구조화된 데이터를 저장, 관리, 조작하는 시스템이며, 데이터의 효율적인 검색과 업데이트를 가능하게 합니다. 데이터베이스 과목에서는 관계형 데이터베이스 모델, SQL 쿼리 언어, 데이터베이스 설계 및 정규화 등을 학습하여 데이터베이스의 구축, 관리, 백업, 복원에 필요한 기술을 습득합니다. 데이터베이스는 다양한 애플리케이션과 시스템에서 데이터를 효율적으로 조작하고 유지하기 위해 필수적인 기반 기술입니다.',
    prev: [],
    next: ['dataBaseDesign'],
    related: ['mysql'],
  },
  sinnor: {
    id: 'sinnor',
    type: 'grade',
    title: '4학년',
    content: '4학년 과목들입니다.',
    prev: ['junior'],
    next: [],
    related: [
      'deepLearning',
      'computerVision',
      'dataBaseDesign',
      'gameProgramming',
    ],
  },
  deepLearning: {
    id: 'deepLearning',
    type: 'class',
    title: '딥러닝',
    content:
      '딥러닝은 인공신경망을 기반으로 한 머신러닝의 한 분야로, 다층 신경망을 사용하여 복잡한 문제를 해결하는 기술입니다. 이 과목에서는 심층 신경망의 구조와 학습 알고리즘을 학습하며, 이미지 인식, 음성 인식, 자연어 처리 등 다양한 분야에서 딥러닝을 활용하는 방법을 배웁니다. 딥러닝은 대용량의 데이터와 강력한 컴퓨팅 리소스를 활용하여 높은 수준의 성능을 달성할 수 있으며, 인공지능 분야에서 혁신적인 발전을 이끌고 있습니다.',
    prev: ['machineLearning'],
    next: [],
    related: ['TensorFlow'],
  },
  computerVision: {
    id: 'computerVision',
    type: 'class',
    title: '컴퓨터비전',
    content:
      '컴퓨터 비전은 컴퓨터 시스템이 이미지나 비디오에서 의미 있는 정보를 추출하고 이해하는 기술을 다루는 과목입니다. 이 과목에서는 이미지 처리, 객체 인식, 추적, 세분화 등을 다루며, 딥러닝과 기계 학습 기법을 활용하여 시각적 데이터를 분석하고 해석하는 방법을 학습합니다. 컴퓨터 비전은 자율 주행 차량, 얼굴 인식, 보안 시스템 등 다양한 응용 분야에서 중요한 역할을 하며, 시각적 정보를 처리하고 이해하는 능력을 강화합니다.',
    prev: ['machineLearning'],
    next: [],
    related: ['TensorFlow'],
  },
  dataBaseDesign: {
    id: 'dataBaseDesign',
    type: 'class',
    title: '데이터베이스설계',
    content:
      '데이터베이스 설계는 구조화된 데이터를 효율적으로 저장하고 검색하기 위해 데이터베이스를 설계하는 과정을 다루는 과목입니다. 이 과목에서는 개체-관계 모델(ER 모델), 정규화, 스키마 설계 등의 기법과 원칙을 학습하여 데이터베이스의 구조를 최적화하고 일관성과 효율성을 유지합니다. 데이터베이스 설계는 데이터의 정확성, 일관성, 보안성을 보장하며, 실제 업무 요구사항을 충족하는 효율적인 데이터베이스 시스템을 구축하기 위해 필수적인 단계입니다.',
    prev: ['dataMining', 'dataBase'],
    next: [],
    related: ['mysql'],
  },
  gameProgramming: {
    id: 'gameProgramming',
    type: 'class',
    title: '게임프로그래밍',
    content:
      '게임 프로그래밍 과목은 게임 개발에 필요한 프로그래밍 기술과 개념을 학습하는 과목으로, 게임 엔진과 언어를 활용하여 다양한 게임 요소를 구현하는 방법을 배웁니다. 이 과목에서는 게임 로직, 그래픽 처리, 물리 시뮬레이션, 사용자 입력 처리 등의 주요 개념과 알고리즘을 다루며, 게임 개발 프로세스와 팀 기반 작업을 경험하고 게임 디자인 원칙을 이해합니다. 게임 프로그래밍 과목은 게임 업계에서의 진로나 개인적인 게임 프로젝트를 위한 필수적인 기술과 지식을 제공합니다.',
    prev: [],
    next: [],
    related: ['unity', 'cs'],
  },

  assembly: {
    id: 'assembly',
    type: 'skill',
    title: '어셈블리어',
    content:
      '어셈블리어(Assembly language)는 기계어와 일대일 대응되는 저급 프로그래밍 언어로, 컴퓨터 아키텍처에서 직접 실행될 수 있는 언어입니다. 어셈블리어는 기계어의 가독성을 높이고 프로그래머가 하드웨어와 직접 상호작용할 수 있도록 해주며, 주로 시스템 프로그래밍이나 하드웨어 제어에 사용됩니다. 어셈블리어는 기본적인 CPU 명령어, 레지스터, 주소지정 등을 사용하여 작성되며, 고급 프로그래밍 언어에 비해 직접적인 제어와 최적화가 가능합니다.',
    prev: [],
    next: [],
    related: ['computerArchitecture', 'C'],
  },

  mysql: {
    id: 'mysql',
    type: 'skill',
    title: 'mysql',
    content:
      'mysql은MySQL은 오픈 소스 관계형 데이터베이스 관리 시스템(RDBMS)으로, 데이터의 저장, 검색, 관리를 위한 기능을 제공하는 소프트웨어입니다. MySQL은 다양한 플랫폼에서 동작하며, 신뢰성과 성능에 중점을 둔 데이터베이스 시스템으로 널리 사용됩니다. SQL(Structured Query Language)을 사용하여 데이터베이스에 쿼리를 실행하고, 데이터의 효율적인 관리와 보안을 지원합니다.',
    prev: [],
    next: [],
    related: ['dataBase', 'dataBaseDesign', 'Hibernate'],
  },

  unity: {
    id: 'unity',
    type: 'skill',
    title: 'unity',
    content:
      'Unity는 게임 개발을 위한 강력한 크로스 플랫폼 게임 엔진으로, 2D 및 3D 게임을 개발할 수 있는 환경을 제공합니다. Unity는 사용자 친화적인 인터페이스와 다양한 도구, 그리고 강력한 스크립팅 언어인 C#을 지원하여 개발자들이 게임의 그래픽, 물리, 인공지능 등을 쉽게 제어하고 구현할 수 있게 합니다. Unity는 게임 개발자들에게 편리하고 생산적인 개발 환경을 제공하며, 다양한 플랫폼에서 게임을 배포할 수 있는 기능을 갖추고 있습니다.',
    prev: [],
    next: [],
    related: ['gameProgramming'],
  },
  cs: {
    id: 'cs',
    type: 'skill',
    title: 'c#',
    content:
      'C#은 Microsoft에서 개발한 다용도 프로그래밍 언어로, 강력한 객체 지향 기능과 간결한 문법을 가지고 있습니다. C#은 .NET 프레임워크와 함께 사용되며, Windows 애플리케이션, 웹 애플리케이션, 게임 개발 등 다양한 플랫폼과 분야에서 널리 활용됩니다. C#은 안정성과 생산성을 강조하는 언어로, 개발자들에게 강력한 개발 도구와 라이브러리를 제공하여 효율적이고 확장 가능한 애플리케이션을 개발할 수 있게 합니다.',
    prev: [],
    next: [],
    related: ['gameProgramming'],
  },

  git: {
    id: 'git',
    type: 'skill',
    title: 'git',
    content:
      'Git은 소스코드 버전 관리 시스템으로, 소스코드의 변경 사항을 추적하고 여러 명의 개발자가 동시에 작업할 수 있도록 지원합니다. Git은 빠른 속도와 분산 버전 관리 기능을 제공하며, 오픈소스 프로젝트에서 널리 사용되고 있습니다. Git은 브랜치 기능을 통해 여러 개발자가 동시에 작업할 수 있고, 변경 사항을 병합할 수 있으며, 변경 이력을 추적할 수 있습니다. Git은 개발자들이 소스코드를 효율적으로 관리하고 협업할 수 있도록 도와줍니다.',
    prev: [],
    next: [],
    related: ['openSource'],
  },

  beakJoon: {
    id: 'beakJoon',
    type: 'competition',
    title: '백준',
    content:
      '백준 온라인 저지는 프로그래밍 문제를 풀고 제출하여 알고리즘 및 코딩 능력을 향상시킬 수 있는 온라인 저지 플랫폼입니다. 이 사이트에서는 다양한 난이도와 유형의 문제를 제공하며, 프로그래밍 언어로 작성한 소스 코드를 채점하여 정확성과 효율성을 평가합니다. 백준은 알고리즘 대회나 코딩 테스트 준비를 위한 유용한 학습 도구로 사용되며, 개발자들 사이에서 널리 활용되고 있습니다.',
    prev: ['algorithm'],
    next: [],
    related: [
      'python',
      'C',
      'Cpp',
      'Java',
      'codeForce',
      'programmers',
      'codeTree',
      'codeUp',
    ],
  },
  codeForce: {
    id: 'codeForce',
    type: 'competition',
    title: '코드포스',
    content:
      '코드 포스(Codeforces)는 경쟁적 프로그래밍 문제를 제공하는 온라인 저지 플랫폼으로, 알고리즘과 자료 구조를 활용한 문제 해결 능력을 향상시킬 수 있습니다. 이 사이트에서는 다양한 난이도와 유형의 문제를 제공하며, 시간 제한과 메모리 제한을 갖춘 환경에서 사용자의 코드를 채점하여 정확성과 효율성을 평가합니다. 코드 포스는 프로그래밍 대회에 참여하고 싶거나 코딩 실력을 향상시키기 위해 많은 개발자들이 활용하는 플랫폼입니다.',
    prev: ['algorithm'],
    next: [],
    related: [
      'python',
      'C',
      'Cpp',
      'Java',
      'beakJoon',
      'programmers',
      'codeTree',
      'codeUp',
    ],
  },
  programmers: {
    id: 'programmers',
    type: 'competition',
    title: '프로그래머스',
    content:
      '프로그래머스(Programmers)는 온라인 프로그래밍 학습 및 코딩 테스트 준비를 위한 플랫폼으로, 다양한 프로그래밍 언어로 알고리즘 문제를 풀 수 있습니다. 이 사이트에서는 실무에 필요한 프로그래밍 기술을 습득하고 코딩 실력을 향상시킬 수 있는 다양한 문제와 과제를 제공합니다. 프로그래머스는 코딩 테스트 대비, 개발자 채용 과정에서 자주 활용되는 플랫폼으로 널리 알려져 있습니다.',
    prev: ['algorithm'],
    next: [],
    related: [
      'python',
      'C',
      'Cpp',
      'Java',
      'beakJoon',
      'codeForce',
      'codeTree',
      'codeUp',
    ],
  },
  codeTree: {
    id: 'codeTree',
    type: 'competition',
    title: '코드트리',
    content:
      '코드트리(CodeTree)는 온라인 코딩 플랫폼으로, 프로그래밍 공부와 문제 해결 능력을 향상시킬 수 있는 학습 리소스를 제공합니다. 이 사이트에서는 다양한 프로그래밍 언어와 기술을 학습할 수 있는 동영상 강의, 예제 코드, 실습 문제 등을 제공하여 개발자들의 기술 습득과 실전 코딩 능력 향상을 돕습니다. 코드트리는 초보부터 중급 개발자까지 다양한 수준의 학습자들에게 유용한 컨텐츠를 제공하며, 쉽게 따라할 수 있는 학습 경로를 제시합니다.',
    prev: ['algorithm'],
    next: [],
    related: [
      'python',
      'C',
      'Cpp',
      'Java',
      'beakJoon',
      'codeForce',
      'programmers',
      'codeUp',
    ],
  },
  codeUp: {
    id: 'codeUp',
    type: 'competition',
    title: '코드업',
    content:
      '코드업(CodeUp)은 입문자를 위한 온라인 프로그래밍 학습 사이트로, 기초적인 프로그래밍 문제를 풀고 해결하는 과정을 경험할 수 있습니다. 이 사이트에서는 다양한 난이도의 문제를 제공하며, C, C++, Java, Python 등 다양한 프로그래밍 언어로 문제를 풀 수 있습니다. 코드업은 프로그래밍 언어의 문법과 기본적인 알고리즘을 학습하고 실력을 향상시키기 위한 좋은 학습 자료를 제공합니다.',
    prev: ['algorithm'],
    next: [],
    related: [
      'python',
      'C',
      'Cpp',
      'Java',
      'beakJoon',
      'codeForce',
      'programmers',
      'codeTree',
    ],
  },
  Modoo_developer_fifth: {
    id: 'Modoo_developer_fifth',
    type: 'competition',
    title: '[모두의연구소] 개발자 취업/이직 : 커리어랩 5기 모집',
    content: '<img src="https://api.linkareer.com/attachments/237251"/>',
    prev: [],
    next: [],
    related: [],
  },
  Seoul_IT_Innovationsquare: {
    id: 'Seoul_IT_Innovationsquare',
    type: 'competition',
    title:
      '[서울 ICT이노베이션스퀘어] AI 서비스 완성! AI+웹 개발 취업캠프 (프론트엔드&백엔드) (~7.4 모집 마감)',
    content:
      '<img src="https://allforyoung-homepage-maycan.s3.ap-northeast-2.amazonaws.com/uploads/post_photos/2023/06/20/0f5e463b689a4224b7be773b303a1469.jpg">',
    prev: [],
    next: [],
    related: [],
  },
  OpenSW_developer_competition: {
    id: 'OpenSW_developer_competition',
    type: 'competition',
    title: '제17회 공개SW 개발자대회 (~07.20)',
    content:
      '<img src="https://allforyoung-homepage-maycan.s3.ap-northeast-2.amazonaws.com/uploads/post_photos/2023/06/21/b38bcc3bdfb040c699182b48f589e85f.png">',
    prev: [],
    next: [],
    related: [],
  },

  JAVA_backend_boot_camp: {
    id: 'JAVA_backend_boot_camp',
    type: 'competition',
    title:
      '[청년취업사관학교] 실무 연계 프로젝트 진행〰️JAVA 백엔드 취업 부트캠프',
    content:
      '<img src="https://allforyoung-homepage-maycan.s3.ap-northeast-2.amazonaws.com/uploads/post_photos/2023/06/07/c26ea49e569e4bd9b8e25464e69a127a.jpg">',
    prev: [],
    next: [],
    related: ['Java'],
  },
};
